# Generated by Django 6.1.1 on 2026-09-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='purchasePrice',
            new_name='purchase_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sellingPrice',
            new_name='selling_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='updatedAt',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='isActive',
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
