# Generated by Django 6.1.1 on 2026-09-28 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_createdat_product_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='photo',
        ),
    ]
