# Generated by Django 6.1.1 on 2026-09-21 03:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_remove_user_email_remove_user_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price', models.PositiveBigIntegerField()),
                ('duration_minutes', models.PositiveIntegerField(help_text='Durasi dalam menit')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('datetime_booking', models.DateTimeField(default=django.utils.timezone.now)),
                ('datetime_service', models.DateTimeField()),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.customer')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.employee')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.pet')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='service.service')),
            ],
        ),
    ]
