# Generated by Django 6.1.1 on 2026-09-22 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_email_remove_user_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('CASHIER', 'Cashier'), ('WAREHOUSE', 'Warehouse'), ('SERVICE', 'Service')], max_length=20),
        ),
    ]
